version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "setup.py" }}
            - v2-dependencies-

      - run:
          name: run linter
          command: |
            pip install flake8-colors
            flake8 --format="$FORMAT" --config=./setup.cfg --show-source
          environment:
            FORMAT: "${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s"

      - run:
          name: install dependencies
          command: |
            # conda config --set auto_update_conda false
            # conda update -n base conda
            # conda config --set always_yes true
            # # deps from requirements.txt are picked up by conda-build
            # #   only list deps for test/coverage here.
            # conda install -qy pytest pytest-cov conda-build
            # conda build --no-test .
            pip install pytest pytest-cov
            pip install codecov
            python setup.py install
      - save_cache:
          paths:
            - /opt/conda
          key: v2-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            # source activate adj
            # Direct matplotlib to use the Agg (non-graphical) backend during
            # circleci runs.
            echo "backend: Agg" > "matplotlibrc"
            pytest -v --cov=gerrychain tests
            codecov
          environment:
            PYTHONHASHSEED: "0"
      - store_artifacts:
          path: test-reports
destination: test-reports
